### ISSUE TITLE
Got error after click a date. 

### ISSUE THREAD

**Issue by jstevenkim** [ikicodedev/calendar_timeline#15]
E/flutter (22154): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 112 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
E/flutter (22154): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (22154): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (22154): #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:112:12)
E/flutter (22154): #3      _ScrollablePositionedListState._startScroll (package:scrollable_positioned_list/src/scrollable_positioned_list.dart:440:36)
E/flutter (22154): #4      _ScrollablePositionedListState._scrollTo (package:scrollable_positioned_list/src/scrollable_positioned_list.dart:407:13)
E/flutter (22154): #5      ItemScrollController.scrollTo (package:scrollable_positioned_list/src/scrollable_positioned_list.dart:193:33)
E/flutter (22154): #6      _CalendarTimelineState._moveToDayIndex (package:calendar_timeline/calendar_timeline.dart:273:20)
E/flutter (22154): #7      _CalendarTimelineState.didUpdateWidget (package:calendar_timeline/calendar_timeline.dart:99:5)
E/flutter (22154): #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:4734:58)
E/flutter (22154): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
E/flutter (22154): #10     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5566:32)
E/flutter (22154): #11     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6001:17)
E/flutter (22154): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
E/flutter (22154): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (22154): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (22154): #15     StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)

**Comment by jstevenkim** [comment]
Fix it by make it as a class and add to a body as below. 

class calendarWidget extends StatelessWidget {
  DateTime _selectedDate = DateTime.now().add(Duration(days: 0));
  @override
  Widget build(BuildContext context){
    return CalendarTimeline(
      initialDate: _selectedDate,
      firstDate: DateTime.now().add(Duration(days: -365)),
      lastDate: DateTime.now().add(Duration(days: 7)),
      onDateSelected: (date) {
        //_selectedDate = date;
        //nowdate = DateFormat('yyyy-MM-dd').format(date);
        //print(nowdate);

      },
      leftMargin: 20,
      monthColor: Colors.deepOrange,
      dayColor: Colors.teal[200],
      dayNameColor: Color(0xFF333A47),
      activeDayColor: Colors.white,
      activeBackgroundDayColor: Colors.redAccent[100],
      dotsColor: Color(0xFF333A47),
      selectableDayPredicate: (date) => date.day != 23,
      locale: 'ko',
    );
  }
}
